<a href="https://colab.research.google.com/github/Princekumarmehta/ADS_LAB/blob/master/Copy_of_python_lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#1a
def count_char_and_display_sentences(filename, char):
    try:
        with open(filename, 'r') as file:
            text = file.read().lower()
            char_count = text.count(char)
            print(f"The character '{char}' appears {char_count} times in the file.")
            sentences = text.split('.')
            for sentence in sentences:
                if sentence.strip().startswith(('A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z')):
                    print(sentence.strip() + '.')

    except FileNotFoundError:
        print("File not found!")

filename = input("Enter the file name: ")
char = input("Enter the character to count: ")
count_char_and_display_sentences(filename, char)


Enter the file name: hi.txt
Enter the character to count: j
The character 'j' appears 1 times in the file.
Hi im Priyanka.
hello world..
Shayari hain..
Jo meri hora hain..


In [6]:
#1b
import struct

def write_records_to_file(filename, num_records):
    try:
        with open(filename, 'wb') as file:
            for _ in range(num_records):
                item_no = int(input("Enter Item No: "))
                item_name = input("Enter Item Name: ")
                qty = int(input("Enter Quantity: "))
                price = float(input("Enter Price per item: "))

                # Packing data into binary format
                packed_data = struct.pack('i 20s i f', item_no, item_name.encode('utf-8'), qty, price)

                # Writing packed data to the file
                file.write(packed_data)

                print("Record added successfully.")
    except IOError:
        print("Error occurred while writing to file.")

def display_records_from_file(filename):
    try:
        with open(filename, 'rb') as file:
            while True:
                packed_data = file.read(struct.calcsize('i 20s i f'))
                if not packed_data:
                    break

                # Unpacking data from binary format
                unpacked_data = struct.unpack('i 20s i f', packed_data)

                item_no, item_name, qty, price = unpacked_data
                item_name = item_name.decode('utf-8')
                amount = qty * price

                # Displaying the records
                print("Item No:", item_no)
                print("Item Name:", item_name.rstrip('\x00'))
                print("Quantity:", qty)
                print("Price per item:", price)
                print("Amount:", amount)
                print()
    except FileNotFoundError:
        print("File not found!")
    except struct.error:
        print("Error occurred while reading from file.")

filename = input("Enter the filename for records: ")
num_records = int(input("Enter the number of records to enter: "))

write_records_to_file(filename, num_records)
print("\nRecords saved to file.")
print("\nDisplaying records from file:")
display_records_from_file(filename)


Enter the filename for records: pika
Enter the number of records to enter: 1
Enter Item No: 1
Enter Item Name: mango
Enter Quantity: 2
Enter Price per item: 3
Record added successfully.

Records saved to file.

Displaying records from file:
Item No: 1
Item Name: mango
Quantity: 2
Price per item: 3.0
Amount: 6.0



In [2]:
#1c
def read_questions(filename):
    try:
        with open(filename, 'r') as file:
            questions = file.readlines()
            return questions
    except FileNotFoundError:
        print(f"Error: {filename} not found.")
        return []

def read_answers(filename):
    try:
        with open(filename, 'r') as file:
            answers = file.readlines()
            return answers
    except FileNotFoundError:
        print(f"Error: {filename} not found.")
        return []

def generate_quiz(questions, answers):
    if len(questions) != len(answers):
        print("Error: Number of questions and answers do not match.")
        return

    print("Quiz:")
    for i in range(len(questions)):
        print(f"{i+1}. {questions[i].strip()}")

    print("\nAnswers:")
    for i in range(len(answers)):
        print(f"{i+1}. {answers[i].strip()}")

questions = read_questions("Questions.txt")
answers = read_answers("Answers.txt")

if questions and answers:
    generate_quiz(questions, answers)


Error: Questions.txt not found.
Error: Answers.txt not found.


In [ ]:
Questions = open("Questions.txt", "r")
Answers = open("Answers.txt", "r")

Q = Questions.read().split("\n")
A = Answers.read().split("\n")

Questions.close()
Answers.close()

print("Total Questions:", len(Q) // 2)  # Dividing by 2 because each question consists of two lines

# Extracting answers from the last character of each line in A
ans = [a.upper() for a in A]  # No need to extract the last character, as each line contains only the answer

for r in range(0, len(Q), 2):
    print("\n", Q[r])
    print("\t", Q[r + 1])
    Flag = True
    while Flag:
        user_input = input("Enter Answer (A/B/C/D): ").upper()
        if user_input in ['A', 'B', 'C', 'D']:
            Flag = False
        else:
            print("Invalid input. Please enter A, B, C, or D.")

    correct_answer = ans[r // 2]
    print("Correct Answer:", correct_answer)  # Display the correct answer corresponding to the question

Total Questions: 3

 1. Who is the prime minister of India? 
	 A. Narendra Modi   B. Shivraj Patil C.Ram  D.Krishna
Enter Answer (A/B/C/D): a
Correct Answer: 1.A 

 2. Who is the President of USA? 
	 A. Donald Trump     B. Joe Biden  C.NOne   D.All
Enter Answer (A/B/C/D): b
Correct Answer: 2.B 

 3.What is the Capital of Karnataka?
	 A. Bengaluru        B.Hyderabad   C.Both    D.None
Enter Answer (A/B/C/D): a
Correct Answer: 3.A


In [ ]:
#2a
#example_file = open("example.txt", "r+")
#bfile = open("bfile.dat", "wb")
#try_file = open("try.txt", "a+")
#btry_file = open("btry.dat", "rb")


In [ ]:
#2b
import pickle

class Employee:
    def __init__(self, name, age, salary, married, kids):
        self.name = name
        self.age = age
        self.salary = salary
        self.married = married
        self.kids = kids

    def __str__(self):
        return f"Employee(name={self.name}, age={self.age}, salary={self.salary}, married={self.married}, kids={self.kids})"

# Function to take employee input from the user
def get_employee_input():
    name = input("Enter employee name: ")
    age = int(input("Enter employee age: "))
    salary = float(input("Enter employee salary: "))
    married = input("Is the employee married? (yes/no): ").lower() == "yes"
    kids = int(input("Enter number of kids the employee has: "))
    return Employee(name, age, salary, married, kids)

# Get employee input from the user
emp1 = get_employee_input()

# Serializing the object and saving it to a file
with open("employee_data.pkl", "wb") as file:
    pickle.dump(emp1, file)

# Loading the serialized object from the file
with open("employee_data.pkl", "rb") as file:
    emp2 = pickle.load(file)

# Displaying the loaded object
print("\nLoaded Employee Object:")
print(emp2)

Enter employee name: john
Enter employee age: 32
Enter employee salary: 320000
Is the employee married? (yes/no): no
Enter number of kids the employee has: 2

Loaded Employee Object:
Employee(name=john, age=32, salary=320000.0, married=False, kids=2)


In [ ]:
#2c
# Opening the file in read mode
with open("Questions.txt", "rb") as f:
    # Moving to the beginning of the file
    f.seek(0)
    print("Current position after seek(0):", f.tell())

    # Moving 100 bytes forward from the current position
    f.seek(100, 1)
    print("Current position after seek(100, 1):", f.tell())

    # Moving 10 bytes backward from the end of the file
    f.seek(-10, 2)
    print("Current position after seek(-10, 2):", f.tell())

    # Moving to the end of the file
    f.seek(0, 2)
    print("Current position after seek(0, 2):", f.tell())


Current position after seek(0): 0
Current position after seek(100, 1): 2
Current position after seek(-10, 2): 256
Current position after seek(0, 2): 266


In [ ]:
#3a
import sqlite3

# Create or connect to the SQLite database
conn = sqlite3.connect('employee.db')
cursor = conn.cursor()

# Create Employee table
cursor.execute('''CREATE TABLE IF NOT EXISTS Employee (
                    emp_ssn TEXT PRIMARY KEY,
                    emp_name TEXT NOT NULL,
                    emp_category TEXT NOT NULL,
                    gross_sal REAL NOT NULL,
                    basic_sal REAL NOT NULL
                    )''')

# Insert sample data into the table
employee_data = [
    ('123-45-6789', 'John Doe', 'Category A', 50000.0, 40000.0),
    ('987-65-4321', 'Jane Smith', 'Category B', 60000.0, 45000.0),
    ('456-78-9012', 'Alice Johnson', 'Category C', 70000.0, 50000.0)
]

cursor.executemany('INSERT INTO Employee VALUES (?, ?, ?, ?, ?)', employee_data)

# Commit the changes
conn.commit()

# Function to compute net salary based on category
def compute_net_salary(category, gross_sal, basic_sal):
    if category == 'Category A':
        return gross_sal - 0.1 * basic_sal  # 10% deduction for Category A
    elif category == 'Category B':
        return gross_sal - 0.15 * basic_sal  # 15% deduction for Category B
    elif category == 'Category C':
        return gross_sal - 0.2 * basic_sal  # 20% deduction for Category C
    else:
        return None

# Query the database and compute net salary for each employee
cursor.execute('SELECT * FROM Employee')
employees = cursor.fetchall()

print("Net Salary for Each Employee:")
for emp in employees:
    net_salary = compute_net_salary(emp[2], emp[3], emp[4])
    print(f"Employee SSN: {emp[0]}, Name: {emp[1]}, Category: {emp[2]}, Net Salary: {net_salary}")

# Close the database connection
conn.close()


Net Salary for Each Employee:
Employee SSN: 123-45-6789, Name: John Doe, Category: Category A, Net Salary: 46000.0
Employee SSN: 987-65-4321, Name: Jane Smith, Category: Category B, Net Salary: 53250.0
Employee SSN: 456-78-9012, Name: Alice Johnson, Category: Category C, Net Salary: 60000.0


In [ ]:
#4
import sqlite3

# Create a connection to the database
conn = sqlite3.connect('library.db')
c = conn.cursor()

# Create Books table
c.execute('''CREATE TABLE IF NOT EXISTS Books
             (id INTEGER PRIMARY KEY,
              name TEXT,
              total_count INTEGER,
              available_count INTEGER)''')

# Function to insert values into the Books table
def insert_book(id, name, total_count):
    available_count = total_count
    c.execute("INSERT INTO Books (id, name, total_count, available_count) VALUES (?, ?, ?, ?)",
              (id, name, total_count, available_count))
    conn.commit()

# Function to borrow a book
def borrow_book(book_id):
    c.execute("SELECT * FROM Books WHERE id=?", (book_id,))
    book = c.fetchone()
    if book:
        if book[3] > 0:
            c.execute("UPDATE Books SET available_count = available_count - 1 WHERE id=?", (book_id,))
            conn.commit()
            print("Book borrowed successfully.")
        else:
            print("Sorry, the book is not available for borrowing.")
    else:
        print("Book not found.")

# Function to return a book
def return_book(book_id):
    c.execute("SELECT * FROM Books WHERE id=?", (book_id,))
    book = c.fetchone()
    if book:
        c.execute("UPDATE Books SET available_count = available_count + 1 WHERE id=?", (book_id,))
        conn.commit()
        print("Book returned successfully.")
    else:
        print("Book not found.")

# Inserting values into the Books table
insert_book(35, 'king', 5)
insert_book(133, 'Harry Potter', 3)

# Sample usage of borrow_book and return_book functions
# User inputs
book_id = input("Enter the book ID: ")
action = input("Do you want to borrow or return the book? (Type 'borrow' or 'return'): ")

# Perform action based on user input
if action == "borrow":
    borrow_book(book_id)
elif action == "return":
    return_book(book_id)

# Close the connection
conn.close()


Enter the book ID: 133
Do you want to borrow or return the book? (Type 'borrow' or 'return'): borrow
Book borrowed successfully.


In [ ]:
#5a
import numpy as np

# Create a 1D NumPy array filled with zeros
zeros_1d = np.zeros(5)  # Creating a 1D array of length 5 filled with zeros
print("1D Array:")
print(zeros_1d)

# Create a 2D NumPy array filled with zeros
zeros_2d = np.zeros((3, 4))  # Creating a 2D array of shape (3, 4) filled with zeros
print("\n2D Array:")
print(zeros_2d)


1D Array:
[0. 0. 0. 0. 0.]

2D Array:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
#5b
import numpy as np

# Create a 1D NumPy array filled with ones
ones_1d = np.ones(5)  # Creating a 1D array of length 5 filled with ones
print("1D Array:")
print(ones_1d)

# Create a 2D NumPy array filled with ones
ones_2d = np.ones((3, 4))  # Creating a 2D array of shape (3, 4) filled with ones
print("\n2D Array:")
print(ones_2d)


1D Array:
[1. 1. 1. 1. 1.]

2D Array:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
#5c
import numpy as np

# Create a sample NumPy array
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Slice elements from index 4 to the end of the array
sliced_array = array[4:]
print("Sliced Array:")
print(sliced_array)


Sliced Array:
[ 5  6  7  8  9 10]


In [ ]:
#5d
import numpy as np

# Create a sample NumPy array
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Slice from the index 3 from the end to index 1 from the end
sliced_array = array[-3:-1]
print("Sliced Array:")
print(sliced_array)


Sliced Array:
[8 9]


In [ ]:
#5e
import numpy as np

def add_arrays(arr1, arr2):
    return arr1 + arr2

# Test the function
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[10, 20], [30, 40]])

result = add_arrays(arr1, arr2)
print("Element-wise sum of the arrays:")
print(result)


Element-wise sum of the arrays:
[[11 22]
 [33 44]]


In [ ]:
#5f
import numpy as np

# Create a NumPy array
array = np.array([[1, 2, 3], [4, 5, 6]])

# Find the sum of all elements in the array
sum_of_elements = np.sum(array)

print("Sum of all elements in the array:", sum_of_elements)


Sum of all elements in the array: 21


In [ ]:
#5g
#1)
# Find the maximum of the given numbers
maximum = max(4, 12, 43.3, 19, 100)
print("Maximum of 4, 12, 43.3, 19, 100:", maximum)
#2)
# Given set of values
values = [4, 12, 43.3, 19, "HelloProgramming"]

# Filter out non-numeric values
numeric_values = [value for value in values if isinstance(value, (int, float))]

# Check if there are numeric values
if numeric_values:
    minimum = min(numeric_values)
    print("Minimum:", minimum)
else:
    print("No numeric values found.")
#3)
# Given list of words
words = ["GoodMorning", "Evening", "algorithm", "programming"]

# Find the word occurring first alphabetically
first_word = min(words)
print("First word alphabetically:", first_word)


Maximum of 4, 12, 43.3, 19, 100: 100
Minimum: 4
First word alphabetically: Evening


In [ ]:
#5h
#1)
import numpy as np

# Create a list
lst = [[4, 3, 2], [2, 1, 4]]

# Convert the list to a NumPy array
array = np.array(lst)

# Sort the array along axis 1 (row-wise)
sorted_array = np.sort(array, axis=1)

print("Sorted array along axis 1:")
print(sorted_array)
#2)
fruits = np.array(["Apple", "Orange", "Banana", "Grapes", "Pineapple"])

# Sort the array in alphabetical order
sorted_indices = np.argsort(fruits)

print("Sorted array of fruits:")
print(fruits[sorted_indices])

print("Index positions:")
print(sorted_indices)


Sorted array along axis 1:
[[2 3 4]
 [1 2 4]]
Sorted array of fruits:
['Apple' 'Banana' 'Grapes' 'Orange' 'Pineapple']
Index positions:
[0 2 3 1 4]


In [ ]:
import pandas as pd

# Create a dictionary with the given data
data = {
    'name': ['Xavier','Ann', 'Jana', 'Yi', 'Robin'],
    'city': ['Mexico City','Toronto', 'Prague', 'Shanghai', 'Manchester'],
    'age': [41, 28, 33, 34, 38],
    'py-score': [88.0, 79.0, 81.0, 80.0,68.0]
}

# Create a DataFrame
df = pd.DataFrame(data,index=[100,101,102,104,105])

# Display the DataFrame
print(df)


       name         city  age  py-score
100  Xavier  Mexico City   41      88.0
101     Ann      Toronto   28      79.0
102    Jana       Prague   33      81.0
104      Yi     Shanghai   34      80.0
105   Robin   Manchester   38      68.0


In [ ]:
# i. Display only first two rows
print("First two rows:")
print(df.head(2))

# ii. Display only last two rows
print("\nLast two rows:")
print(df.tail(2))

# iii. Extract the py-score of Toronto column
py_score_toronto = df.loc[df['city'] == 'Toronto', 'py-score']
print("\nPy-score of Toronto:")
print(py_score_toronto)

# iv. Display loc of last row
last_row_loc = df.iloc[-1]
print("\nLocation of last row:")
print(last_row_loc)

# v. Calculate mean, min, max, standard deviation
mean_py_score = df['py-score'].mean()
min_py_score = df['py-score'].min()
max_py_score = df['py-score'].max()
std_py_score = df['py-score'].std()

print("\nMean Py-score:", mean_py_score)
print("Min Py-score:", min_py_score)
print("Max Py-score:", max_py_score)
print("Standard Deviation of Py-score:", std_py_score)

# vi. Print the basic stats using describe() method
print("\nBasic stats of DataFrame:")
print(df.describe())


First two rows:
       name         city  age  py-score
100  Xavier  Mexico City   41      88.0
101     Ann      Toronto   28      79.0

Last two rows:
      name        city  age  py-score
104     Yi    Shanghai   34      80.0
105  Robin  Manchester   38      68.0

Py-score of Toronto:
101    79.0
Name: py-score, dtype: float64

Location of last row:
name             Robin
city        Manchester
age                 38
py-score          68.0
Name: 105, dtype: object

Mean Py-score: 79.2
Min Py-score: 68.0
Max Py-score: 88.0
Standard Deviation of Py-score: 7.19027120489902

Basic stats of DataFrame:
             age   py-score
count   5.000000   5.000000
mean   34.800000  79.200000
std     4.969909   7.190271
min    28.000000  68.000000
25%    33.000000  79.000000
50%    34.000000  80.000000
75%    38.000000  81.000000
max    41.000000  88.000000


In [ ]:
import pandas as pd
import numpy as np

# Create a dictionary with the given data
data = {
    'Date': ['2009-02-11', '2009-02-12', '2009-02-13', '2009-02-17', '2009-02-18'],
    'High': [30.20, 30.28, 30.45, 29.35, 29.35],
    'Low': [29.41, 29.32, 29.96, 28.74, 28.56],
    'Close': [29.87, 30.24, 30.10, 28.90, 28.92]
}

# Create a DataFrame
df = pd.DataFrame(data)

# Create a boolean series
bools = pd.Series([True, False, False, True, False])

# Filter the DataFrame based on the boolean series
filtered_df = df[bools]

# Display the filtered DataFrame
print(filtered_df)


         Date   High    Low  Close
0  2009-02-11  30.20  29.41  29.87
3  2009-02-17  29.35  28.74  28.90
